export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALURE = "LOGIN_FALURE";
export const LOGOUT = "LOGOUT";

export const USERS_REQUEST = "USERS_REQUEST"
export const USERS_SUCCESS = "USERS_SUCCESS"
export const USERS_FALURE = "USERS_FALURE"

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST"
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS"
export const USER_CREATE_FALURE = "USER_CREATE_FALURE"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FALURE = "USER_UPDATE_FALURE"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FALURE = "USER_DELETE_FALURE"

export const USER_PROFILES_REQUEST = "USER_PROFILES_REQUEST"
export const USER_PROFILES_SUCCESS = "USER_PROFILES_SUCCESS"
export const USER_PROFILES_FALURE = "USER_PROFILES_FALURE"

export const USER_PROFILES_CREATE_REQUEST = "USER_PROFILES_CREATE_REQUEST"
export const USER_PROFILES_CREATE_SUCCESS = "USER_PROFILES_CREATE_SUCCESS"
export const USER_PROFILES_CREATE_FALURE = "USER_PROFILES_CREATE_FALURE"

export const USER_PROFILES_UPDATE_REQUEST = "USER_PROFILES_UPDATE_REQUEST"
export const USER_PROFILES_UPDATE_SUCCESS = "USER_PROFILES_UPDATE_SUCCESS"
export const USER_PROFILES_UPDATE_FALURE = "USER_PROFILES_UPDATE_FALURE"

export const USER_PROFILES_DELETE_REQUEST = "USER_PROFILES_DELETE_REQUEST"
export const USER_PROFILES_DELETE_SUCCESS = "USER_PROFILES_DELETE_SUCCESS"
export const USER_PROFILES_DELETE_FALURE = "USER_PROFILES_DELETE_FALURE"

//------------

export const PERMISSIONS_REQUEST = "PERMISSIONS_REQUEST"
export const PERMISSIONS_SUCCESS = "PERMISSIONS_SUCCESS"
export const PERMISSIONS_FALURE = "PERMISSIONS_FALURE"

export const PERMISSION_CREATE_REQUEST = "PERMISSION_CREATE_REQUEST"
export const PERMISSION_CREATE_SUCCESS = "PERMISSION_CREATE_SUCCESS"
export const PERMISSION_CREATE_FALURE = "PERMISSION_CREATE_FALURE"

export const PERMISSION_UPDATE_REQUEST = "PERMISSION_UPDATE_REQUEST"
export const PERMISSION_UPDATE_SUCCESS = "PERMISSION_UPDATE_SUCCESS"
export const PERMISSION_UPDATE_FALURE = "PERMISSION_UPDATE_FALURE"

export const PERMISSION_DELETE_REQUEST = "PERMISSION_DELETE_REQUEST"
export const PERMISSION_DELETE_SUCCESS = "PERMISSION_DELETE_SUCCESS"
export const PERMISSION_DELETE_FALURE = "PERMISSION_DELETE_FALURE"

export const GENERICS_REQUEST = "GENERICS_REQUEST"
export const GENERICS_SUCCESS = "GENERICS_SUCCESS"
export const GENERICS_FALURE = "GENERICS_FALURE"

export const GENERIC_CREATE_REQUEST = "GENERIC_CREATE_REQUEST"
export const GENERIC_CREATE_SUCCESS = "GENERIC_CREATE_SUCCESS"
export const GENERIC_CREATE_FALURE = "GENERIC_CREATE_FALURE"

export const GENERIC_UPDATE_REQUEST = "GENERIC_UPDATE_REQUEST"
export const GENERIC_UPDATE_SUCCESS = "GENERIC_UPDATE_SUCCESS"
export const GENERIC_UPDATE_FALURE = "GENERIC_UPDATE_FALURE"

export const GENERIC_DELETE_REQUEST = "GENERIC_DELETE_REQUEST"
export const GENERIC_DELETE_SUCCESS = "GENERIC_DELETE_SUCCESS"
export const GENERIC_DELETE_FALURE = "GENERIC_DELETE_FALURE"

// ------------

export const FILES_REQUEST = "FILES_REQUEST"
export const FILES_SUCCESS = "FILES_SUCCESS"
export const FILES_FALURE = "FILES_FALURE"

export const FILE_CREATE_REQUEST = "FILE_CREATE_REQUEST"
export const FILE_CREATE_SUCCESS = "FILE_CREATE_SUCCESS"
export const FILE_CREATE_FALURE = "FILE_CREATE_FALURE"

export const FIELD_FILE_CREATE_REQUEST = "FIELD_FILE_CREATE_REQUEST"
export const FIELD_FILE_CREATE_SUCCESS = "FIELD_FILE_CREATE_SUCCESS"
export const FIELD_FILE_CREATE_FALURE = "FIELD_FILE_CREATE_FALURE"

export const FILE_DELETE_REQUEST = "FILE_DELETE_REQUEST"
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS"
export const FILE_DELETE_FALURE = "FILE_DELETE_FALURE"

export const FILE_DOWNLOAD_REQUEST = "FILE_DOWNLOAD_REQUEST"
export const FILE_DOWNLOAD_SUCCESS = "FILE_DOWNLOAD_SUCCESS"
export const FILE_DOWNLOAD_FALURE = "FILE_DOWNLOAD_REQUEST"

// ------------

export const RESET_GENERIC_REQUEST = "RESET_GENERIC_REQUEST"
export const RESET_GENERIC_SUCCESS = "RESET_GENERIC_SUCCESS"
export const RESET_GENERIC_FALURE = "RESET_GENERIC_FALURE"

// ------

export const EVENTS_REQUEST = "EVENTS_REQUEST"
export const EVENTS_SUCCESS = "EVENTS_SUCCESS"
export const EVENTS_FALURE = "EVENTS_FALURE"

export const EVENTS_CREATE_REQUEST = "EVENTS_CREATE_REQUEST"
export const EVENTS_CREATE_SUCCESS = "EVENTS_CREATE_SUCCESS"
export const EVENTS_CREATE_FALURE = "EVENTS_CREATE_FALURE"

export const EVENTS_UPDATE_REQUEST = "EVENTS_UPDATE_REQUEST"
export const EVENTS_UPDATE_SUCCESS = "EVENTS_UPDATE_SUCCESS"
export const EVENTS_UPDATE_FALURE = "EVENTS_UPDATE_FALURE"

export const EVENTS_DELETE_REQUEST = "EVENTS_DELETE_REQUEST"
export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS"
export const EVENTS_DELETE_FALURE = "EVENTS_DELETE_FALURE"

// ------

export const TASKS_REQUEST = "TASKS_REQUEST"
export const TASKS_SUCCESS = "TASKS_SUCCESS"
export const TASKS_FALURE = "TASKS_FALURE"

export const TASKS_CREATE_REQUEST = "TASKS_CREATE_REQUEST"
export const TASKS_CREATE_SUCCESS = "TASKS_CREATE_SUCCESS"
export const TASKS_CREATE_FALURE = "TASKS_CREATE_FALURE"

export const TASKS_UPDATE_REQUEST = "TASKS_UPDATE_REQUEST"
export const TASKS_UPDATE_SUCCESS = "TASKS_UPDATE_SUCCESS"
export const TASKS_UPDATE_FALURE = "TASKS_UPDATE_FALURE"

export const TASKS_DELETE_REQUEST = "TASKS_DELETE_REQUEST"
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS"
export const TASKS_DELETE_FALURE = "TASKS_DELETE_FALURE"
